# Generated by Django 4.0.4 on 2022-05-12 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0010_alter_firmstoredata_datescanned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmstoredata',
            name='datescanned',
            field=models.DateField(default=datetime.date(2022, 5, 12)),
        ),
        migrations.AlterField(
            model_name='tempqrstore',
            name='datescanned',
            field=models.DateField(default=datetime.date(2022, 5, 12)),
        ),
    ]
